# Numpy exercises


#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [2]:
a=np.zeros([10])
print (a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [3]:
np.add(a,b)

NameError: name 'b' is not defined

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [ ]:
a[4]=5
print(a)

#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [ ]:
b=np.arange(10,50)
print(b)

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [ ]:
c=np.arange(0,51)
d=c[::-1]
print(d)

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [ ]:
e=np.arange(0,9)
f=e.reshape(3,3)
print(f)

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [ ]:
z=np.array([1,2,0,0,4,0])
b=np.nonzero(z)

print(b)

#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [ ]:
r=np.random.randint(0,21,(1,3,3))
print(r)

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [ ]:
t=np.random.random((10,10))
m=np.max(t)
n=np.min(t)

print(m)
print(n)

#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [ ]:
x=np.random.random(30)
m=np.mean(x)
print(m)

#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [ ]:
e=np.arange(0,11)
v=e[3:9]
print(v)

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [ ]:
w=np.random.randint(0,10,(20))
print(w)
for i in range(len(w)):
    #print(i)
    if w[i]<5:
    
        w[i] *= 2 
        
print(w)        

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [ ]:
d=np.array([1,5,6,2,-2,23,45])

c=np.where(d%2==0)
print(c)

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [ ]:
q=np.arange(0,21)
a=np.where(q%3==0)
print(q[a])

#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [ ]:
d=np.array([0,1,2,3,4]*5)
d.shape=(5,5)
print(d)

#### 17. Create a 3x5 numpy array filled with random numbers from 1 to 10.

#### 17. Ստեղծեք 1-ից 10 պատահական թվերով լցված (3, 5) չափերով numpy array։

In [31]:
p=np.random.randint(1,11,(3,5))
print(p)

[[ 2  4  9 10  5]
 [ 9  2  2  6  6]
 [ 7  8  6  8  1]]


#### 18. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

#### 18. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [ ]:
g=np.zeros(10)
g[4]=3
print(g)

#### 19. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

#### 19. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [ ]:
h=np.arange(3,15)
print(h)

        

#### 20. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array. 

#### 20. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [29]:
def array1(a):

    while np.mean(a)>=5:
        a=a/2
    print(a)
    
    

             
                    
                  
               
    
       
    
         

In [30]:
array1(np.array([0,1,2,3,4,5,6,7,25,20]))

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5 12.5 10. ]


#### 21. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an inputand returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

#### 21. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [51]:
def array2(a=np.random.randint(1,11,(5,5))):
            print(a)
            print(a[...,0])
            print(a[...,1])
            print(a[...,2])
            print(a[...,3])

In [52]:
array2()

[[ 1  9  4  6  1]
 [ 8  3  4  6  8]
 [ 8  1  7  2  1]
 [ 5  1  5  3  1]
 [ 5 10  1 10  7]]
[1 8 8 5 5]
[ 9  3  1  1 10]
[4 4 7 5 1]
[ 6  6  2  3 10]


In [56]:
def array3(a=np.random.randint(1,11,(5,5))):
            print(a)
            print(a[0,...])
            print(a[1,...])
            print(a[2,...])
            print(a[3,...])
            print(a[4,...])

In [57]:
array3()

[[ 4  1  7  6  7]
 [ 1  7  2  7 10]
 [ 3  1  1  7  8]
 [ 4  4  6  2  5]
 [ 3  8  7  5  1]]
[4 1 7 6 7]
[ 1  7  2  7 10]
[3 1 1 7 8]
[4 4 6 2 5]
[3 8 7 5 1]
